# Generated by Django 5.0.1 on 2024-02-13 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineinformation',
            name='medicine_type',
            field=models.CharField(blank=True, choices=[('LIQUID', 'LIQUID'), ('TABLET', 'TABLET'), ('CAPSULES', 'CAPSULES')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='patientrecords',
            name='medication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.medicineinformation'),
        ),
    ]
