# Generated by Django 5.0.1 on 2024-02-13 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_medicineinformation_medicine_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecords',
            name='dosage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.dosage'),
        ),
        migrations.AlterField(
            model_name='patientrecords',
            name='medication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.medicineinformation'),
        ),
    ]
