# Generated by Django 5.0.1 on 2024-02-13 06:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patientrecords_dosage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicinePrescription',
            fields=[
                ('prescriptionID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prescription_name', models.CharField(max_length=100)),
                ('prescription_created_date', models.DateTimeField(auto_now_add=True)),
                ('dosage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.dosage')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.medicineinformation')),
            ],
            options={
                'ordering': ['-prescription_created_date'],
            },
        ),
        migrations.AddField(
            model_name='patientrecords',
            name='prescrition',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.medicineprescription'),
        ),
    ]
