# Generated by Django 5.0.1 on 2024-02-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_medicineprescription_patientrecords_prescrition'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineinformation',
            name='medicine_created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
