# Generated by Django 5.0.1 on 2024-02-13 06:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_medicineinformation_medicine_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosage',
            name='dose_uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='medicineinformation',
            name='medicine_uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
