# Generated by Django 5.0.1 on 2024-02-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_dosage_dose_uid_medicineinformation_medicine_uid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dosage',
            options={'ordering': ['-dose_created_date']},
        ),
        migrations.AddField(
            model_name='dosage',
            name='dose_created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
